// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vaXB4FHZ6SNi1iiDACOH7SRwfA2j0MM',
    appId: '1:11887258970:web:fc8c703e578c2a3b88d763',
    messagingSenderId: '11887258970',
    projectId: 'movia-flutterflow',
    authDomain: 'movia-flutterflow.firebaseapp.com',
    storageBucket: 'movia-flutterflow.firebasestorage.app',
    measurementId: 'G-T29WTV01EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXqUshMGiVNUEmlv7epDUBtLmqn1xopo',
    appId: '1:11887258970:android:fc32b2bd4f5ab64188d763',
    messagingSenderId: '11887258970',
    projectId: 'movia-flutterflow',
    storageBucket: 'movia-flutterflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15FWrCq_vhG9tpM44hJZ4WAz2U77jAPk',
    appId: '1:11887258970:ios:b42d28183c07abbf88d763',
    messagingSenderId: '11887258970',
    projectId: 'movia-flutterflow',
    storageBucket: 'movia-flutterflow.firebasestorage.app',
    androidClientId: '11887258970-lmagfu05ho3gls97eo8bi9a8c0h29lql.apps.googleusercontent.com',
    iosClientId: '11887258970-e1jbmpchu3ethe1e6nin3pp7noq894qe.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.movia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15FWrCq_vhG9tpM44hJZ4WAz2U77jAPk',
    appId: '1:11887258970:ios:b42d28183c07abbf88d763',
    messagingSenderId: '11887258970',
    projectId: 'movia-flutterflow',
    storageBucket: 'movia-flutterflow.firebasestorage.app',
    androidClientId: '11887258970-lmagfu05ho3gls97eo8bi9a8c0h29lql.apps.googleusercontent.com',
    iosClientId: '11887258970-e1jbmpchu3ethe1e6nin3pp7noq894qe.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.movia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8vaXB4FHZ6SNi1iiDACOH7SRwfA2j0MM',
    appId: '1:11887258970:web:4b947edd62f481b788d763',
    messagingSenderId: '11887258970',
    projectId: 'movia-flutterflow',
    authDomain: 'movia-flutterflow.firebaseapp.com',
    storageBucket: 'movia-flutterflow.firebasestorage.app',
    measurementId: 'G-50T2GZPRNC',
  );
}
